# Úkol č. 2 - regrese

* Termíny jsou uvedeny na [courses.fit.cvut.cz](https://courses.fit.cvut.cz/BI-ML1/homeworks/index.html).
* Pokud odevzdáte úkol po prvním termínu ale před nejzazším termínem, budete penalizování -12 body, pozdější odevzdání je bez bodu.
* V rámci tohoto úkolu se musíte vypořádat s regresní úlohou, s příznaky různých typů a s chybějícími hodnotami.
* Před tím, než na nich postavíte predikční model, je třeba je nějakým způsobem převést do číselné reprezentace.
    
> **Úkoly jsou zadány tak, aby Vám daly prostor pro invenci. Vymyslet _jak přesně_ budete úkol řešit, je důležitou součástí zadání a originalita či nápaditost bude také hodnocena!**

Využívejte buňky typu `Markdown` k vysvětlování Vašeho postupu. Za nepřehlednost budeme strhávat body.

## Zdroj dat

Budeme se zabývat predikcí délky dožití v různých zemích a letech.
K dispozici máte trénovací data v souboru `data.csv` a data na vyhodnocení v souboru `evaluation.csv`.

#### Seznam příznaků:

* Year - Rok
* Status - Status rozvinuté nebo rozvojové země
* Life expectancy - Délka dožití v letech - **cílová proměnná, kterou budete predikovat**
* Adult Mortality - Úmrtnost dospělých bez ohledu na pohlaví (pravděpodobnost, že osoby, které dosáhly věku 15 let, zemřou před dosažením věku 60 let (uvedeno na 1 000 osob)).
* infant deaths - počet zemřelých kojenců na 1000 obyvatel
* Alcohol - Alkohol, zaznamenaná spotřeba na obyvatele (15+) (v litrech čistého alkoholu)
* percentage expenditure - Výdaje na zdravotnictví v procentech hrubého domácího produktu na obyvatele (%)
* Hepatitis B - pokrytí očkováním proti hepatitidě B (HepB) u dětí ve věku 1 roku (%)
* Measles - Spalničky - počet hlášených případů na 1000 obyvatel
* BMI - průměrný index tělesné hmotnosti celé populace
* under-five deaths - počet úmrtí dětí do pěti let na 1000 obyvatel
* Polio - proočkovanost proti dětské obrně (Pol3) u dětí ve věku 1 roku (%)
* Total expenditure - Výdaje vládních institucí na zdravotnictví jako procento celkových vládních výdajů (%)
* Diphtheria - pokrytí očkováním proti záškrtu, tetanu a černému kašli (DTP3) u jednoletých dětí (%)
* HIV/AIDS - počet úmrtí na 1 000 živě narozených dětí na HIV/AIDS (0-4 roky)
* GDP - hrubý domácí produkt na obyvatele (v USD)
* Population - počet obyvatel země
* thinness 1-19 years - podíl dětí ve věku 10-19 let s indexem tělesné hmotnosti (BMI) menším než 2 směrodatné odchylky pod mediánem (%)
* thinness 5-9 years - podíl dětí ve věku 5-9 let s indexem tělesné hmotnosti (BMI) menším než 2 směrodatné odchylky pod mediánem (%)
* Income composition of resources - Index lidského rozvoje z hlediska příjmového složení zdrojů (index v rozmezí 0 až 1)
* Schooling - počet let školní docházky (roky)


## Pokyny k vypracování

**Body zadání**, za jejichž (poctivé) vypracování získáte **25 bodů**: 
  * V notebooku načtěte data ze souboru `data.csv`. Vhodným způsobem si je rozdělte na podmnožiny, které Vám poslouží pro trénování (trénovací), porovnávání modelů (validační) a následnou predikci výkonnosti finálního modelu (testovací).
    
  * Proveďte základní předzpracování dat:
    * Projděte si jednotlivé příznaky a transformujte je do vhodné podoby pro použití ve vybraném regresním modelu.
    * Nějakým způsobem se vypořádejte s chybějícími hodnotami. _Pozor na metodické chyby!_
    * Můžete využívat i vizualizace. Vše stručně ale náležitě komentujte.
<br /><br />
  * Vytvořte **vlastní implementaci náhodného lesa**. Použijte k tomu níže předpřipravenou kostru.
  
  * Na připravená data postupně aplikujte Vaši předchozí implementaci modelu náhodného lesa, dále jeden z modelů **lineární regrese** nebo **hřebenové regrese**, a alespoň jeden další model podle Vašeho uvážení, přičemž pro každý z těchto modelů přiměřeně:
    * Okomentujte vhodnost daného modelu pro daný typ úlohy.
    * Experimentujte s normalizací (standardizace/min-max), pokud pro daný model očekáváte její příznivý vliv.
    * Vyberte si hlavní hyperparametry k ladění a najděte jejich nejlepší hodnoty (vzhledem k RMSE).
    * Pro model s nejlepšími hodnotami hyperparametrů určete jeho chybu pomocí RMSE a MAE. _Pozor na metodické chyby!_
    * Získané výsledky vždy řádně okomentujte.
<br /><br />
  * Ze všech zkoušených možností v předchozím kroku vyberte finální model a odhadněte, jakou chybu (RMSE) můžete očekávat na nových datech, která jste doposud neměli k dispozici. _Pozor na metodické chyby!_
    
  * Nakonec načtěte vyhodnocovací data ze souboru `evaluation.csv`. Pomocí finálního modelu napočítejte predikce pro tato data. Vytvořte soubor `results.csv`, ve kterém získané predikce uložíte s využitím tří sloupců: **Country**, **Year** a **Life expectancy**. Tento soubor též odevzdejte (uložte do repozitáře vedle notebooku).

  * Ukázka prvních řádků souboru `results.csv`:
  
```
Country,Year,Life expectancy
Peru,2012,71.4
Peru,2013,72.6
...
```


## Poznámky k odevzdání

  * Řiďte se pokyny ze stránky https://courses.fit.cvut.cz/BI-ML1/homeworks/index.html.

In [1]:
import math
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from random import randrange
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Ridge, LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.neighbors import KNeighborsRegressor

import warnings

In [2]:
df = pd.read_csv("data.csv")

Náhodně rozdělím data na trénovací, testovací a validační.

In [3]:
Xdata = df.drop("Life expectancy", axis = 1)
Ydata = df["Life expectancy"]
rd_seed = 333
Xtrain, Xtest, Ytrain, Ytest = train_test_split(Xdata, Ydata, test_size=0.4, random_state=rd_seed) 
Xval, Xtest, Yval, Ytest = train_test_split(Xtest, Ytest, test_size=0.5, random_state=rd_seed)

nektera data maji nesmyslne hodnoty - dalo by se je nějak upravit například zkoušet posouvat desetinnou čárku u dat, která jsou řádově mimo. Některá data nedávají smysl vůbec, například populace v afgánistánu.

In [4]:
pd.set_option('display.max_rows', None)
df.head(100)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
5,Afghanistan,2010,Developing,58.8,279.0,74,0.01,79.679367,66.0,1989,...,66.0,9.20,66.0,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2
6,Afghanistan,2009,Developing,58.6,281.0,77,0.01,56.762217,63.0,2861,...,63.0,9.42,63.0,0.1,445.893298,284331.0,18.6,18.7,0.434,8.9
7,Afghanistan,2008,Developing,58.1,287.0,80,0.03,25.873925,64.0,1599,...,64.0,8.33,64.0,0.1,373.361116,2729431.0,18.8,18.9,0.433,8.7
8,Afghanistan,2007,Developing,57.5,295.0,82,0.02,10.910156,63.0,1141,...,63.0,6.73,63.0,0.1,369.835796,26616792.0,19.0,19.1,0.415,8.4
9,Afghanistan,2006,Developing,57.3,295.0,84,0.03,17.171518,64.0,1990,...,58.0,7.43,58.0,0.1,272.563770,2589345.0,19.2,19.3,0.405,8.1
10,Afghanistan,2005,Developing,57.3,291.0,85,0.02,1.388648,66.0,1296,...,58.0,8.70,58.0,0.1,25.294130,257798.0,19.3,19.5,0.396,7.9
11,Afghanistan,2004,Developing,57.0,293.0,87,0.02,15.296066,67.0,466,...,5.0,8.79,5.0,0.1,219.141353,24118979.0,19.5,19.7,0.381,6.8
12,Afghanistan,2003,Developing,56.7,295.0,87,0.01,11.089053,65.0,798,...,41.0,8.82,41.0,0.1,198.728544,2364851.0,19.7,19.9,0.373,6.5
13,Afghanistan,2002,Developing,56.2,3.0,88,0.01,16.887351,64.0,2486,...,36.0,7.76,36.0,0.1,187.845950,21979923.0,19.9,2.2,0.341,6.2
14,Afghanistan,2001,Developing,55.3,316.0,88,0.01,10.574728,63.0,8762,...,35.0,7.80,33.0,0.1,117.496980,2966463.0,2.1,2.4,0.340,5.9
15,Afghanistan,2000,Developing,54.8,321.0,88,0.01,10.424960,62.0,6532,...,24.0,8.20,24.0,0.1,114.560000,293756.0,2.3,2.5,0.338,5.5
16,Albania,2015,Developing,77.8,74.0,0,4.60,364.975229,99.0,0,...,99.0,6.00,99.0,0.1,3954.227830,28873.0,1.2,1.3,0.762,14.2
17,Albania,2014,Developing,77.5,8.0,0,4.51,428.749067,98.0,0,...,98.0,5.88,98.0,0.1,4575.763787,288914.0,1.2,1.3,0.761,14.2
18,Albania,2013,Developing,77.2,84.0,0,4.76,430.876979,99.0,0,...,99.0,5.66,99.0,0.1,4414.723140,289592.0,1.3,1.4,0.759,14.2
19,Albania,2012,Developing,76.9,86.0,0,5.14,412.443356,99.0,9,...,99.0,5.59,99.0,0.1,4247.614380,2941.0,1.3,1.4,0.752,14.2
20,Albania,2011,Developing,76.6,88.0,0,5.37,437.062100,99.0,28,...,99.0,5.71,99.0,0.1,4437.178680,295195.0,1.4,1.5,0.738,13.3
21,Albania,2010,Developing,76.2,91.0,1,5.28,41.822757,99.0,10,...,99.0,5.34,99.0,0.1,494.358832,291321.0,1.4,1.5,0.725,12.5
22,Albania,2009,Developing,76.1,91.0,1,5.79,348.055952,98.0,0,...,98.0,5.79,98.0,0.1,4114.136545,2927519.0,1.5,1.6,0.721,12.2
23,Albania,2008,Developing,75.3,1.0,1,5.61,36.622068,99.0,0,...,99.0,5.87,99.0,0.1,437.539647,2947314.0,1.6,1.6,0.713,12.0
24,Albania,2007,Developing,75.9,9.0,1,5.58,32.246552,98.0,22,...,99.0,6.10,98.0,0.1,363.136850,29717.0,1.6,1.7,0.703,11.6
25,Albania,2006,Developing,74.2,99.0,1,5.31,3.302154,98.0,68,...,97.0,5.86,97.0,0.1,35.129300,2992547.0,1.7,1.8,0.696,11.4
26,Albania,2005,Developing,73.5,15.0,1,5.16,26.993121,98.0,6,...,97.0,6.12,98.0,0.1,279.142931,311487.0,1.8,1.8,0.685,10.8
27,Albania,2004,Developing,73.0,17.0,1,4.54,221.842800,99.0,7,...,98.0,6.38,97.0,0.1,2416.588235,326939.0,1.8,1.9,0.681,10.9
28,Albania,2003,Developing,72.8,18.0,1,4.29,14.719289,97.0,8,...,97.0,6.27,97.0,0.1,189.681557,339616.0,1.9,2.0,0.674,10.7
29,Albania,2002,Developing,73.3,15.0,1,3.73,104.516916,96.0,16,...,98.0,6.30,98.0,0.1,1453.642777,3511.0,2.0,2.1,0.670,10.7
30,Albania,2001,Developing,73.6,14.0,1,4.25,96.205571,96.0,18,...,97.0,6.00,97.0,0.1,1326.973390,36173.0,2.1,2.1,0.662,10.6
31,Albania,2000,Developing,72.6,11.0,1,3.66,91.711541,96.0,662,...,97.0,6.26,97.0,0.1,1175.788981,38927.0,2.1,2.2,0.656,10.7
32,Algeria,2015,Developing,75.6,19.0,21,NaN,0.000000,95.0,63,...,95.0,NaN,95.0,0.1,4132.762920,39871528.0,6.0,5.8,0.743,14.4
33,Algeria,2014,Developing,75.4,11.0,21,0.01,54.237318,95.0,0,...,95.0,7.21,95.0,0.1,547.851700,39113313.0,6.0,5.8,0.741,14.4
34,Algeria,2013,Developing,75.3,112.0,21,0.53,544.450743,95.0,25,...,95.0,7.12,95.0,0.1,5471.866766,38338562.0,5.9,5.8,0.737,14.4
35,Algeria,2012,Developing,75.1,113.0,21,0.66,555.926083,95.0,18,...,95.0,6.14,95.0,0.1,5564.825660,37565847.0,5.9,5.8,0.732,14.4
36,Algeria,2011,Developing,74.9,116.0,21,0.56,509.002041,95.0,112,...,95.0,5.29,95.0,0.1,5432.252300,36819558.0,5.9,5.8,0.724,14.0
37,Algeria,2010,Developing,74.7,119.0,21,0.45,430.717586,95.0,103,...,95.0,5.12,95.0,0.1,4463.394675,36117637.0,5.9,5.8,0.714,13.6
38,Algeria,2009,Developing,74.4,123.0,20,0.50,352.063642,94.0,107,...,94.0,5.36,95.0,0.1,3868.831230,3546576.0,6.0,5.9,0.705,13.1
39,Algeria,2008,Developing,74.1,126.0,20,0.46,43.087173,91.0,217,...,92.0,4.20,93.0,0.1,495.254866,3486715.0,6.0,5.9,0.697,12.6
40,Algeria,2007,Developing,73.8,129.0,20,0.44,320.323924,9.0,0,...,95.0,3.82,95.0,0.1,3935.183343,34376.0,6.0,5.9,0.690,12.3
41,Algeria,2006,Developing,73.4,132.0,20,0.36,270.240196,8.0,944,...,95.0,3.36,95.0,0.1,3464.617900,33777915.0,6.1,6.0,0.686,12.3
42,Algeria,2005,Developing,72.9,136.0,19,0.50,2.548923,83.0,2302,...,88.0,3.24,88.0,0.1,31.122378,33288437.0,6.1,6.0,0.680,12.0
43,Algeria,2004,Developing,72.3,14.0,19,0.45,220.393699,81.0,3289,...,86.0,3.54,86.0,0.1,2598.982300,3283196.0,6.2,6.1,0.673,11.7
44,Algeria,2003,Developing,71.7,146.0,20,0.34,25.018523,NaN,15374,...,87.0,3.60,87.0,0.1,294.335560,3243514.0,6.3,6.1,0.663,11.5
45,Algeria,2002,Developing,71.6,145.0,20,0.36,148.511984,NaN,5862,...,86.0,3.73,86.0,0.1,1774.336730,3199546.0,6.3,6.2,0.653,11.1
46,Algeria,2001,Developing,71.4,145.0,20,0.23,147.986071,NaN,2686,...,89.0,3.84,89.0,0.1,1732.857979,31592153.0,6.4,6.3,0.644,10.9
47,Algeria,2000,Developing,71.3,145.0,21,0.25,154.455944,NaN,0,...,86.0,3.49,86.0,0.1,1757.177970,3118366.0,6.5,6.4,0.636,10.7
48,Angola,2015,Developing,52.4,335.0,66,NaN,0.000000,64.0,118,...,7.0,NaN,64.0,1.9,3695.793748,2785935.0,8.3,8.2,0.531,11.4
49,Angola,2014,Developing,51.7,348.0,67,8.33,23.965612,64.0,11699,...,68.0,3.31,64.0,2.0,479.312240,2692466.0,8.5,8.3,0.527,11.4
50,Angola,2013,Developing,51.1,355.0,69,8.10,35.958573,77.0,8523,...,67.0,4.26,77.0,2.3,484.616884,2599834.0,8.6,8.5,0.523,11.4
51,Angola,2012,Developing,56.0,358.0,72,8.24,256.122524,75.0,4458,...,75.0,3.30,75.0,2.6,4598.249988,259615.0,8.8,8.6,0.508,10.3
52,Angola,2011,Developing,51.0,361.0,75,8.06,239.891392,72.0,1449,...,73.0,3.38,71.0,2.5,4299.128890,24218565.0,8.9,8.8,0.495,9.4
53,Angola,2010,Developing,49.6,365.0,78,7.80,191.653741,77.0,1190,...,81.0,3.39,77.0,2.5,3529.534820,23369131.0,9.1,9.0,0.488,9.0
54,Angola,2009,Developing,49.1,369.0,81,7.01,212.922933,61.0,2807,...,63.0,4.37,6.0,2.5,3347.844850,22549547.0,9.3,9.2,0.480,8.5
55,Angola,2008,Developing,48.7,371.0,84,7.07,249.910196,69.0,265,...,65.0,3.84,69.0,2.6,3868.578883,2175942.0,9.5,9.4,0.468,8.1
56,Angola,2007,Developing,48.2,375.0,87,6.35,184.821345,73.0,1014,...,75.0,3.38,73.0,2.6,2878.837144,2997687.0,9.6,9.6,0.454,7.7
57,Angola,2006,Developing,47.7,381.0,90,5.84,25.086888,NaN,765,...,36.0,4.54,34.0,2.5,262.415149,2262399.0,9.8,9.7,0.439,7.2
58,Angola,2005,Developing,47.4,382.0,92,5.04,98.191451,NaN,258,...,39.0,4.10,38.0,2.6,1443.991929,19552542.0,1.0,9.9,0.426,6.8
59,Angola,2004,Developing,47.1,386.0,94,3.53,8.866777,NaN,29,...,4.0,4.71,4.0,2.5,141.868440,18865716.0,1.2,1.1,0.415,6.4
60,Angola,2003,Developing,46.8,388.0,95,3.49,35.933491,NaN,1196,...,4.0,4.41,4.0,2.4,779.468356,1823369.0,1.4,1.3,0.406,5.9
61,Angola,2002,Developing,46.5,391.0,96,2.82,24.037942,NaN,11945,...,37.0,3.63,41.0,2.3,711.181716,17572649.0,1.5,1.5,0.401,5.5
62,Angola,2001,Developing,45.7,44.0,97,2.58,30.359936,NaN,9046,...,41.0,5.38,38.0,2.1,526.168743,16983266.0,1.7,1.7,0.391,5.1
63,Angola,2000,Developing,45.3,48.0,97,1.85,15.881493,NaN,2219,...,3.0,2.79,28.0,2.0,555.296942,1644924.0,1.9,1.9,0.382,4.6
64,Antigua and Barbuda,2015,Developing,76.4,13.0,0,NaN,0.000000,99.0,0,...,86.0,NaN,99.0,0.2,13566.954100,NaN,3.3,3.3,0.784,13.9
65,Antigua and Barbuda,2014,Developing,76.2,131.0,0,8.56,2422.999774,99.0,0,...,96.0,5.54,99.0,0.2,12888.296670,NaN,3.3,3.3,0.782,13.9
66,Antigua and Barbuda,2013,Developing,76.1,133.0,0,8.58,1991.430372,99.0,0,...,98.0,5.33,99.0,0.2,12224.864160,NaN,3.3,3.3,0.781,13.9
67,Antigua and Barbuda,2012,Developing,75.9,134.0,0,8.18,2156.229842,98.0,0,...,97.0,5.39,98.0,0.2,12565.441970,NaN,3.3,3.3,0.778,13.8
68,Antigua and Barbuda,2011,Developing,75.7,136.0,0,7.84,1810.875316,99.0,0,...,99.0,5.65,99.0,0.1,11929.349910,NaN,3.3,3.3,0.782,14.1
69,Antigua and Barbuda,2010,Developing,75.6,138.0,0,7.84,1983.956937,98.0,0,...,99.0,5.63,98.0,0.1,12126.876140,NaN,3.3,3.3,0.783,14.1
70,Antigua and Barbuda,2009,Developing,75.4,14.0,0,7.82,149.358735,98.0,0,...,98.0,4.86,99.0,0.1,1312.466920,NaN,3.4,3.3,0.788,14.2
71,Antigua and Barbuda,2008,Developing,75.2,142.0,0,8.27,180.776270,98.0,0,...,99.0,4.69,99.0,0.1,1473.319230,NaN,3.4,3.3,0.786,14.4
72,Antigua and Barbuda,2007,Developing,75.0,144.0,0,8.64,257.966531,97.0,0,...,98.0,4.27,99.0,0.1,14252.294520,NaN,3.4,3.3,0.781,14.5
73,Antigua and Barbuda,2006,Developing,74.8,145.0,0,8.93,216.314694,99.0,0,...,99.0,4.34,99.0,0.1,12724.393770,NaN,3.4,3.4,0.773,14.7
74,Antigua and Barbuda,2005,Developing,74.6,147.0,0,8.15,1455.608186,99.0,0,...,98.0,4.41,99.0,0.1,11371.938950,NaN,3.5,3.4,0.000,0.0
75,Antigua and Barbuda,2004,Developing,74.4,149.0,0,7.28,22.862952,97.0,0,...,97.0,4.21,97.0,0.1,1352.837400,NaN,3.5,3.4,0.000,0.0
76,Antigua and Barbuda,2003,Developing,74.2,151.0,0,7.16,1158.065259,99.0,0,...,99.0,4.53,99.0,0.1,9739.825560,NaN,3.5,3.5,0.000,0.0
77,Antigua and Barbuda,2002,Developing,74.0,153.0,0,7.21,927.407585,99.0,0,...,93.0,4.41,98.0,0.1,9386.716452,NaN,3.6,3.5,0.000,0.0
78,Antigua and Barbuda,2001,Developing,73.8,154.0,0,7.51,163.767698,96.0,0,...,99.0,4.48,97.0,0.1,9358.154162,NaN,3.6,3.5,0.000,0.0
79,Antigua and Barbuda,2000,Developing,73.6,156.0,0,7.27,1127.743470,NaN,0,...,96.0,4.13,95.0,0.1,9875.161736,NaN,3.7,3.6,0.000,0.0
80,Argentina,2015,Developing,76.3,116.0,8,NaN,0.000000,94.0,0,...,93.0,NaN,94.0,0.1,13467.123600,43417765.0,1.0,0.9,0.826,17.3
81,Argentina,2014,Developing,76.2,118.0,8,7.93,847.371746,94.0,1,...,92.0,4.79,94.0,0.1,12245.256450,42981515.0,1.0,0.9,0.825,17.3
82,Argentina,2013,Developing,76.0,119.0,8,8.28,1001.796332,94.0,0,...,99.0,4.99,94.0,0.1,12976.636420,42539925.0,1.0,0.9,0.823,17.3
83,Argentina,2012,Developing,75.9,12.0,9,8.35,1133.558003,91.0,2,...,99.0,5.20,91.0,0.1,12969.771200,4296739.0,1.0,0.9,0.822,17.2
84,Argentina,2011,Developing,75.7,12.0,9,8.11,1504.329462,91.0,3,...,93.0,5.89,91.0,0.1,12726.983600,41656879.0,1.0,0.9,0.816,17.1
85,Argentina,2010,Developing,75.5,121.0,10,8.15,187.610955,94.0,17,...,95.0,6.55,94.0,0.1,1276.265000,41223889.0,1.0,0.9,0.802,16.8
86,Argentina,2009,Developing,75.6,126.0,10,8.33,1398.042623,94.0,3,...,97.0,7.63,94.0,0.1,8161.369660,479947.0,1.0,0.9,0.794,16.5
87,Argentina,2008,Developing,75.4,126.0,10,8.41,1413.735430,9.0,0,...,94.0,6.66,93.0,0.1,8953.359275,4382389.0,1.0,0.9,0.792,16.3
88,Argentina,2007,Developing,74.8,129.0,10,8.16,1105.659031,85.0,0,...,92.0,6.49,91.0,0.1,7193.617640,3997224.0,1.1,0.9,0.788,16.3
89,Argentina,2006,Developing,75.2,127.0,11,7.75,961.177468,84.0,0,...,92.0,6.68,91.0,0.1,5878.761270,3955889.0,1.1,0.9,0.782,16.1
90,Argentina,2005,Developing,74.9,127.0,11,7.53,96.166534,88.0,0,...,95.0,6.85,98.0,0.1,576.883829,39145488.0,1.1,1.0,0.780,16.3
91,Argentina,2004,Developing,74.7,13.0,11,7.63,719.366380,81.0,0,...,91.0,6.84,98.0,0.1,4251.574348,38728696.0,1.1,1.0,0.775,16.3
92,Argentina,2003,Developing,74.1,137.0,11,7.62,57.584674,73.0,0,...,95.0,8.22,96.0,0.1,333.437600,3839379.0,1.2,1.0,0.770,16.4
93,Argentina,2002,Developing,74.1,138.0,12,7.81,470.186915,66.0,0,...,94.0,8.31,93.0,0.1,2579.193168,3788937.0,1.2,1.0,0.776,16.3
94,Argentina,2001,Developing,74.0,138.0,12,7.76,123.012867,NaN,0,...,85.0,9.38,83.0,0.1,717.694674,3747159.0,1.2,1.1,0.771,15.6
95,Argentina,2000,Developing,74.1,137.0,12,7.68,1349.025282,NaN,6,...,88.0,9.21,83.0,0.1,7669.273916,3757452.0,1.2,1.1,0.764,15.0
96,Armenia,2015,Developing,74.8,118.0,1,NaN,0.000000,94.0,33,...,96.0,NaN,94.0,0.1,369.654776,291695.0,2.1,2.2,0.741,12.7
97,Armenia,2014,Developing,74.6,12.0,1,3.91,295.608714,93.0,13,...,95.0,4.48,93.0,0.1,3994.712355,29622.0,2.1,2.1,0.739,12.7
98,Armenia,2013,Developing,74.4,123.0,1,3.79,279.429081,95.0,10,...,96.0,4.55,95.0,0.1,3843.591213,289359.0,2.1,2.1,0.736,12.7
99,Armenia,2012,Developing,74.4,121.0,1,3.89,274.152699,95.0,0,...,96.0,4.48,95.0,0.1,3684.848100,2881922.0,2.0,2.1,0.732,12.7

### Nahrazení NaN  
dole seznam příznaků, kde se vyskytují nany a jak je potencionálně nahradit.

pokud má stát v příznaku víc než polovinu hodnot NaN, musím je zreplikovat od podobných států. Jinak vezmu medián ostatních hodot toho příznaku


Alcohol - south sudan je jediný, kde chybí dost - medián všech států

Hepatitis B - státy se stejnou dětskou úmrtností

Polio - státy se stejnou dětskou úmrtností

Total expenditure - státy se stejným developmentem

Diphtheria - státy se stejnou dětskou úmrtností

GDP - státy se stejným developmentem

Population - toto je podle mě nezávislé úplně - medián všech států

BMI - ve státech kde chybí víc jak půl, chybí i příznak thinness. Proto opužiju státy se stejným developmentem

thinness  1-19 years - státy se stejným developmentem

thinness 5-9 years - státy se stejným developmentem

Income composition of resources - median zemí se stejnou školní docházkou a developmentem

Schooling - median států se stejným percentage expenditure - když davájí peníze na zdravotnictvi tak snad i na školství

In [5]:
nan_cols = [i for i in df.columns if df[i].isnull().any()]
nan_cols

['Alcohol',
 'Hepatitis B',
 'BMI',
 'Polio',
 'Total expenditure',
 'Diphtheria',
 'GDP',
 'Population',
 'thinness  1-19 years',
 'thinness 5-9 years',
 'Income composition of resources',
 'Schooling']

In [6]:
# dostane dataset kde se jména států shodují - vrátí true pokud je v datech v příznaku column víc než půlka nan
def more_than_half_nulls(data, column):
    nulls = 0
    for i in range(data.shape[0]):
        if pd.isnull(data.iloc[i][column]):
            nulls += 1
    
    # bugfixing
    if nulls-2 > data.shape[0]/2:
        return True
    return False
    
    
def fill_nan_by_state_mean(mean_value, dataframe, state, column):
    mask = dataframe['Country'] == state

    dataframe.loc[mask, column] = dataframe.loc[mask, column].fillna(mean_value)
    return dataframe
  
    
# v datasetu nahradí všechny nan příznaky ve sloupci column u státu state
# k výpočtu používá trénovací data, což může trochu zhoršit čitelnost kódu
def substitue_nan(data, column, state):    
#     print(column, state)
    matching_rows = data[data["Country"] == state]
    
#     print("matching_rows = ", matching_rows.shape[0])
    if not matching_rows.empty:
        first_row = matching_rows.iloc[0]
    else:
        return data
    
    mean_value = None
    if more_than_half_nulls(Xtrain.loc[Xtrain["Country"] == state], column):
        if column == "Alcohol":
            print("here")
            mean_value = Xtrain[column].median()
        elif column == "Hepatitis B":
            mean_value = Xtrain.loc[Xtrain["infant deaths"] == first_row["infant deaths"]][column].median()
        elif column == "Polio":
            mean_value = Xtrain.loc[Xtrain["infant deaths"] == first_row["infant deaths"]][column].median()
        elif column == "BMI":
            mean_value = Xtrain.loc[Xtrain["Status"] == first_row["Status"]][column].median()
        elif column == "Total expenditure":
            mean_value = Xtrain.loc[Xtrain["Status"] == first_row["Status"]][column].median()
        elif column == "Diphtheria":
            mean_value = Xtrain.loc[Xtrain["infant deaths"] == first_row["infant deaths"]][column].median()
        elif column == "GDP":
            mean_value = Xtrain.loc[Xtrain["Status"] == first_row["Status"]][column].median()
        elif column == "Population":
            mean_value = Xtrain[column].median()
        elif column == "thinness  1-19 years":
            mean_value = Xtrain.loc[Xtrain["Status"] == first_row["Status"]][column].median()
        elif column == "thinness 5-9 years":
            mean_value = Xtrain.loc[Xtrain["Status"] == first_row["Status"]][column].median()
        elif column == "Income composition of resources":
            mean_value = Xtrain.loc[(Xtrain["Schooling"] == first_row["Schooling"]) & (Xtrain["Status"] == first_row["Status"])][column].median()
        elif column == "Schooling":
            mean_value = Xtrain.loc[Xtrain["percentage expenditure"] == first_row["percentage expenditure"]][column].median() 
        
    else:
        mean_value = Xtrain.loc[Xtrain["Country"] == state][column].median()
        

    data = fill_nan_by_state_mean(mean_value, data, state, column)
#     print("mean_value = ", mean_value)
    return data


def fill_mean(data):
    nan_cols = [i for i in data.columns if data[i].isnull().any()]
   
    for col in nan_cols:
        mean_v = Xtrain[col].median()
        data[col] = data[col].fillna(mean_v)
    return data


# dolní všechny nan
def substitue_all_nan(data):
    nan_cols = [i for i in data.columns if data[i].isnull().any()]
#     print("naser si", nan_cols)
    for col in nan_cols:
#         print(data[col])
        null_in_row = data[data[col].isnull()]
#         print(null_in_row)
        states = null_in_row["Country"].unique()
#         print(states)
        for state in states:
#             print(col, state)
            data = substitue_nan(data, col, state)

    # pro jistotu, aby nezustal nikde nan
    data = fill_mean(data)
    return data

# za všechny nany dosadí -1 = mohlo by být užitečné pro les, použiju jako hyperparametr
def fill_negative(data):
    data = data.fillna(-1)
    return data

### Číselné příznaky

In [7]:
pd.set_option('display.max_rows', None)
Xdata["Country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', "Côte d'Ivoire", 'Cabo Verde',
       'Cambodia', 'Cameroon', 'Canada', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran (Islamic Republic of)',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Micronesia (Federated States of)',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Republic of Korea', 'Republic of Moldova',
       'Romania', 'Russian Federation', 'Rwanda', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand',
       'The former Yugoslav republic of Macedonia', 'Timor-Leste', 'Togo',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

Status má jenom dvě unikátní hodnoty, tak jsem se je rozhodl předělat na 0 a 1 bez použití dummy sloupce.

In [8]:
Xtrain["Status"].unique()

array(['Developing', 'Developed'], dtype=object)

In [9]:
def code_development(data):
    if data == "Developing":
         data = "0"
    elif data == "Developed":
        data = "1"
    return data

def convert_status(data):
    data["Status"] = data["Status"].apply(code_development)
    data["Status"] = data["Status"].astype(int)
    return data

In [10]:
asia = ['Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei Darussalam', 'Cambodia', 'China', 'Georgia', 'India', 'Indonesia', 'Iran (Islamic Republic of)', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic", 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'Oman', 'Pakistan', 'Qatar', 'Republic of Korea', 'Saudi Arabia', 'Singapore', 'Sri Lanka', 'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'Timor-Leste', 'Turkey', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Viet Nam', 'Yemen']

europe = ['Albania', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Republic of Moldova', 'Romania', 'Russian Federation', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'The former Yugoslav republic of Macedonia', 'United Kingdom of Great Britain and Northern Ireland']

africa = ['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', "Côte d'Ivoire", 'Cabo Verde', 'Cameroon', 'Central African Republic', 'Chad', 'Comoros', 'Congo', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan', 'Tanzania', 'Togo', 'Uganda', 'Zambia', 'Zimbabwe']

australia_oceania = ['Australia', 'Fiji', 'Kiribati', 'Marshall Islands', 'Micronesia (Federated States of)', 'Nauru', 'New Zealand', 'Palau', 'Papua New Guinea', 'Samoa', 'Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu']

north_america = ['Antigua and Barbuda', 'Bahamas', 'Barbados', 'Belize', 'Canada', 'Costa Rica', 'Cuba', 'Dominican Republic', 'El Salvador', 'Grenada', 'Guatemala', 'Haiti', 'Honduras', 'Jamaica', 'Mexico', 'Nicaragua', 'Panama', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Trinidad and Tobago', 'United States of America']

south_america = ['Argentina', 'Bolivia (Plurinational State of)', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela (Bolivarian Republic of)']

Pro velké množství unikátních hodnot příznaku country jsem se rozhodl je rozdělit do kategorií, pro které jsem vytvořil dummy příznaky. Poloha země na kontinentu by mohla hrát významnou roli pro věk dožití.

In [11]:
# přidá pro každý kontinent dummy příznak
def add_continent_dummies(data):
    return data.assign(asia=0, europe=0, africa=0, australia_oceania=0, north_america=0, south_america=0)
    
# rozdělí země do kontinentů (ty mam vytvořené výše v polích)  
def assign_country(data):
    for index, row_data in data.iterrows():
        if row_data["Country"] in asia:
            data.at[index, "asia"] = 1
        elif row_data["Country"] in europe:
            data.at[index, "europe"] = 1
        elif row_data["Country"] in africa:
            data.at[index, "africa"] = 1
        elif row_data["Country"] in australia_oceania:
            data.at[index, "australia_oceania"] = 1
        elif row_data["Country"] in north_america:
            data.at[index, "north_america"] = 1
        elif row_data["Country"] in south_america:
            data.at[index, "south_america"] = 1
    return data
        
def drop_country(data):
    data = data.drop('Country', axis=1)
    return data

def country_to_int(data):
    data = add_continent_dummies(data)
    data = assign_country(data)
    data = drop_country(data)
    return data

In [12]:
def transform_data(data):
    data = convert_status(data)
    data = country_to_int(data)
    return data

### Moje impementace random forest

In [13]:
# Váš kód zde


########################################################
# Předpřipravená kostra modelu náhodného lesa
class CustomRandomForest:
    trees = []

    # vytvořím prázdné stromy s jejich příslušnými parametry a uložím si je do pole
    def __init__(self, n_estimators, max_samples, max_depth, **kwargs):

        self.n_estimators = n_estimators
        self.max_samples = max_samples
        self.max_depth = max_depth
        self.kwargs = kwargs
        
        for i in range(self.n_estimators):
               self.trees.append(DecisionTreeRegressor(max_depth=self.max_depth, **kwargs)) 
        
    # vygeneruje n náhoných čísel mezi 0 až Xtrain velikost, kde n je velikost * max_samples parametr   
    def bootstrap(self, size) -> list:
        result = []
        values = size * self.max_samples
        for num in range(int(values)):
            result.append(randrange(size))
        
        return result
            
    
    # natrénuje každý strom
    def fit(self, X, y):
        if isinstance(X, pd.DataFrame):
            X = X.values
 
        for tree in self.trees:
            positions = self.bootstrap(X.shape[0])
            
            xtmp = X[positions]
            ytmp = y.iloc[positions]
            
            tree.fit(xtmp, ytmp)
            


    def predict_val(self, X) -> int:
        result = []

        if isinstance(X, pd.DataFrame):
            X = X.values  # Convert DataFrame to NumPy array

        # Ensure that the shape is (1, -1) for a single sample with any number of features
        X = X.reshape(1, -1)

        for tree in self.trees:
            prediction = tree.predict(X)
            result.append(prediction)

        res = np.mean(result)

        return res
    
        
    def predict(self, X):
        if isinstance(X, pd.DataFrame):
            X = X.values
        
        # vytvořím pole, do kterého uložím výsledek
        y_predicted = np.zeros((X.shape[0],))
        
        for num in range(X.shape[0]):
            tmp = self.predict_val(X[num, :])

            y_predicted[num] = tmp
        
        return y_predicted

### Trénování modelů

Vytvořím si 2 sady dat s různým řešením nan, které budu používat na modely.

In [14]:
Xtrain_m = substitue_all_nan(Xtrain)
Xval_m = substitue_all_nan(Xval)
Xtest_m = substitue_all_nan(Xtest)

Xtrain_n = fill_negative(Xtrain)
Xval_n = fill_negative(Xval)
Xtest_n = fill_negative(Xtest)

here

Převedu příznaky na číselné

In [15]:
Xtrain_m = transform_data(Xtrain_m)
Xval_m = transform_data(Xval_m)
Xtest_m = transform_data(Xtest_m)

Xtrain_n = transform_data(Xtrain_n)
Xval_n = transform_data(Xval_n)
Xtest_n = transform_data(Xtest_n)

Vyberu si jeden z datasetů, který budu používat a zkusím ho normalizovat i standardizovat

In [16]:
scaler_mm = MinMaxScaler()
scaler_std = StandardScaler()

# current_data_train = Xtrain_m
# current_data_val = Xval_m
# current_data_test = Xtest_m
current_data_train = Xtrain_n
current_data_val = Xval_n
current_data_test = Xtest_n

scaler_mm.fit(current_data_train)
scaler_std.fit(current_data_train)

X_train_minmax = scaler_mm.transform(current_data_train)
X_train_std = scaler_std.transform(current_data_train)
X_val_minmax = scaler_mm.transform(current_data_val)
X_val_std = scaler_std.transform(current_data_val)
X_test_minmax = scaler_mm.transform(current_data_test)
X_test_std = scaler_std.transform(current_data_test)

In [36]:
Yval.shape
X_val_minmax.shape

(544, 26)

### Hřebenová regrese 
lineární jsem usoudil že nebude efektivní, kvůli závislosti příznaků

Vyzkouším různé hodnoty hyperparametru lambda a interceptu. Dále jako hyperparametr použiju, zda budu pracovat se škálováním dat

In [37]:
lam = 1
intercept = False
best_rmse = 10000000
# (0-no scaler, 1-minmax, 2-standard)
best_data = 0

all_data = [current_data_train, X_train_minmax, X_train_std]
all_val = [current_data_val, X_val_minmax, X_val_std]

for i in range(0, 35):
    inter = True
    for j in range(2):
        for dat in range(3):
            clf_ridge = Ridge(alpha=i, fit_intercept=inter)
            clf_ridge.fit(all_data[dat], Ytrain)
            RMSE_val_ridge = mean_squared_error(Yval, clf_ridge.predict(all_val[dat]), squared = False)
            
            if RMSE_val_ridge < best_rmse:
                best_rmse = RMSE_val_ridge
                lam = i
                intercept = inter
                best_data = dat
            inter = False

/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=3.15968e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=3.03861e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=3.38045e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=3.2512e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=3.60126e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=3.46386e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=3.82212e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=3.67661e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=4.04304e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=3.88945e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=4.26403e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=4.10239e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=4.48509e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=4.31544e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=4.70624e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=4.52859e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=4.92748e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=4.74186e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=5.14882e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=4.95525e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=5.37026e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=5.16877e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=5.59181e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=5.38241e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=5.81348e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=5.59619e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=6.03526e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=5.81011e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=6.25718e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=6.02417e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=6.47922e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=6.23838e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=6.70139e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=6.45273e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=6.9237e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=6.66723e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.14616e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=6.88189e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.36875e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.0967e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.59149e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.31166e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.81438e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.52679e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=8.03743e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.74207e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=8.26062e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=7.95752e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=8.48397e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=8.17312e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=8.70747e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=8.38889e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=8.93113e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=8.60483e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=9.15495e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=8.82092e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=9.37893e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=9.03718e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=9.60306e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=9.25361e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=9.82736e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=9.4702e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=1.00518e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=9.68696e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=1.02764e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=9.90388e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=1.05012e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=1.0121e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=1.07262e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/mara/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:200: LinAlgWarning: Ill-conditioned matrix (rcond=1.03382e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

In [39]:
print(best_rmse, lam, intercept, best_data)

3.8465523637160643 5 False 0

výstup při nahrazení nanu -1

nejlepší výstup: 3.837246865761791 lambda = 6 intercept = False neupravená data (0)

vypočítání nanu

nejlepší výstup: 3.8465523637160643 lambda = 5 intercept = False neupravená data (0)

### Náhodný les

Níže jsou dva pokusy o natrénování lesa s ruznými hyperparametry. V prvním jsem se zajímal jen o počet stromů a z části i o hloubku. V druhém jsem zkoumal efekt i v závislosti na velikosti množiny na které stromy trénuju a škálování vstupních dat.

Kvůli značné časové náročnosti už jsem nezkoumal další hyperparametry jako například max_features

In [21]:
estimators = 0
data_portion = 0
best_depth = 0

best_rmse = 10000000

# (0-no scaler, 1-minmax, 2-standard)
best_data = 0
dat = 1

all_data = [Xtrain, X_train_minmax, X_train_std]
all_val = [Xval, X_val_minmax, X_val_std]

for est in range(155, 180, 15):
    for depth in range(20, 24, 2):
        forest = CustomRandomForest(n_estimators=est, max_samples=0.3, max_depth=depth)
        forest.fit(all_data[dat], Ytrain)
        RMSE_val_ridge = mean_squared_error(Yval, forest.predict(all_val[dat]), squared = False)

        if RMSE_val_ridge < best_rmse:
            best_rmse = RMSE_val_ridge
            estimators = est
            data_portion = 0.3
            best_depth = depth
            best_data = dat
        
    print(est)

155
170

In [22]:
print(best_rmse, estimators, data_portion, best_depth, best_data)

2.3318129196492023 170 0.3 20 1

výstup při nahrazení nanu -1 
2.327442610581602 145 0.3 22 1

nejlepší výstup: 2.327442610581602 počet stromů = 145 podíl dat = 0.3 hloubka = 22 normalizovaná data (1)

nany vypočítány funkcí

nejlepší výstup: 2.3472484907423614 počet stromů = 215 podíl dat = 0.3 hloubka = 18 normalizovaná data (1)

Zde zkoumám jak výsledek ovlivňují i ostatní hyperparametry, které volím s hodnotami kolem nejlepších hodnot z předchozího měření

In [23]:
estimators = 0
data_portion = 0
best_depth = 0

best_rmse = 10000000

# (0-no scaler, 1-minmax, 2-standard)
best_data = 0

all_data = [current_data_train, X_train_minmax, X_train_std]
all_val = [current_data_val , X_val_minmax, X_val_std]

for est in range(135, 150, 5):
    for depth in range(17, 21):
        for samples in np.arange(0.4, 0.6, 0.2):
            for dat in range(3):
                forest = CustomRandomForest(n_estimators=est, max_samples=samples, max_depth=depth)
                forest.fit(all_data[dat], Ytrain)
                RMSE_val_ridge = mean_squared_error(Yval, forest.predict(all_val[dat]), squared = False)
                
                if RMSE_val_ridge < best_rmse:
                    best_rmse = RMSE_val_ridge
                    estimators = est
                    data_portion = samples
                    best_depth = depth
                    best_data = dat
    print(est)

135
140
145

In [24]:
print(best_rmse, estimators, data_portion, best_depth, best_data)

2.212086059209918 135 0.4 18 2

nahrazení nanu -1

nejlepší výstup: 2.212086059209918 počet stromů = 135 podíl dat = 0.4 hloubka = 18 standardizovaná data (2)

nany vypočítány funkcí

nejlepší výstup: 2.2248201161385905 počet stromů = 215 podíl dat = 0.4 hloubka = 20 neupravená data (0)

### KNN

Jako poslední zkusim knn model kde budu zkoumat vliv hyperparametrů počet sousedů, metrika (jen eukleidovská geometrie), vliv vzdálenosti sousedů od zkoumaného bodu a škálování.

In [24]:
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
# data std, minmax a default

best_rmse = 1000000
# (0-no scaler, 1-minmax, 2-standard)
best_data = 5
best_neighbours = 0
best_weights = None # uniform / distance
best_metrics = 1

all_data = [current_data_train, X_train_minmax, X_train_std]
all_val = [current_data_val, X_val_minmax, X_val_std]


for neigh in range(1, 50):
    for met in range(1, 3): # might try more
        for weight in ["uniform", "distance"]:
            knn = KNeighborsRegressor(n_neighbors=neigh, p=met, weights=weight)
            for i in range(3):
                knn.fit(all_data[i], Ytrain)
                RMSE_val_ridge = mean_squared_error(Yval, knn.predict(all_val[i]), squared = False)

                if RMSE_val_ridge < best_rmse:
                    best_data = i
                    best_neighbours = neigh
                    best_weights = weight
                    best_metrics = met
                    best_rmse = RMSE_val_ridge

In [25]:
print(best_rmse, best_neighbours, best_data, best_metrics, best_weights)

2.4140499569915668 4 2 1 distance

nany nahrazeny -1

nejlepší výstup: 2.4426835268754292 sousedi= 3 standardizovaná data (2) metrika = 1 váha = distance

nany vypočítány funkcí

nejlepší výstup: 2.4140499569915668 sousedi = 4 standardizovaná data (2) metrika = 1 váha = distance

nejlépe skóruje les na datech, kde nany jsou nahrazené -1 a standardizované

In [25]:
forest = CustomRandomForest(n_estimators=135, max_samples=0.4, max_depth=18)
forest.fit(X_train_std, Ytrain)

In [26]:
print("rmse = ", mean_squared_error(Ytest, forest.predict(X_test_std), squared = False))
print("mae = ", mean_absolute_error(Ytest, forest.predict(X_test_std)))

rmse =  2.056789927095609
mae =  1.2985884988941516

### Finální předpověď

In [36]:
evaluation = pd.read_csv("evaluation.csv")
result = evaluation[["Country", "Year"]]

Použiju na data úpravu jako na původní data, pro vzor mediánů použiju trénovací data

In [37]:
evaluation = fill_negative(evaluation)
evaluation = transform_data(evaluation)
evaluation = scaler_std.transform(evaluation)

In [38]:
life_expect = forest.predict(evaluation)

In [39]:
result.insert(2, "Life expectancy", 0)
result["Life expectancy"] = life_expect

In [40]:
result.to_csv("results.csv", index=False)

In [41]:
df = pd.read_csv("results.csv")

In [42]:
df.head(10)

      Country  Year  Life expectancy
0  Azerbaijan  2015        73.908737
1  Azerbaijan  2014        74.588797
2  Azerbaijan  2013        74.644639
3  Azerbaijan  2012        74.225243
4  Azerbaijan  2011        74.304221
5  Azerbaijan  2010        74.143968
6     Belgium  2015        83.682758
7     Belgium  2014        83.344365
8     Belgium  2013        82.680875
9     Belgium  2012        82.784583